import pieces


chesspieces = {"6_0": {"type": pieces.Pawn, "color": "B"},
               "6_1": {"type": pieces.Pawn, "color": "B"},
               "6_2": {"type": pieces.Pawn, "color": "B"},
               "6_3": {"type": pieces.Pawn, "color": "B"},
               "6_4": {"type": pieces.Pawn, "color": "B"},
               "6_5": {"type": pieces.Pawn, "color": "B"},
               "6_6": {"type": pieces.Pawn, "color": "B"},
               "6_7": {"type": pieces.Pawn, "color": "B"},
               "7_0": {"type": pieces.Rook, "color": "B"},
               "7_1": {"type": pieces.Knight, "color": "B"},
               "7_2": {"type": pieces.Bishop, "color": "B"},
               "7_3": {"type": pieces.Queen, "color": "B"},
               "7_4": {"type": pieces.King, "color": "B"},
               "7_5": {"type": pieces.Bishop, "color": "B"},
               "7_6": {"type": pieces.Knight, "color": "B"},
               "7_7": {"type": pieces.Rook, "color": "B"},
               "0_0": {"type": pieces.Rook, "color": "W"},
               "0_1": {"type": pieces.Knight, "color": "W"},
               "0_2": {"type": pieces.Bishop, "color": "W"},
               "0_3": {"type": pieces.Queen, "color": "W"},
               "0_4": {"type": pieces.King, "color": "W"},
               "0_5": {"type": pieces.Bishop, "color": "W"},
               "0_6": {"type": pieces.Knight, "color": "W"},
               "0_7": {"type": pieces.Rook, "color": "W"},
               "1_0": {"type": pieces.Pawn, "color": "W"},
               "1_1": {"type": pieces.Pawn, "color": "W"},
               "1_2": {"type": pieces.Pawn, "color": "W"},
               "1_3": {"type": pieces.Pawn, "color": "W"},
               "1_4": {"type": pieces.Pawn, "color": "W"},
               "1_5": {"type": pieces.Pawn, "color": "W"},
               "1_6": {"type": pieces.Pawn, "color": "W"},
               "1_7": {"type": pieces.Pawn, "color": "W"},
               }


chesspieces_dummy = {"6_0": {"type": pieces.Pawn, "color": "B"},
                     # "6_1": {"type": pieces.Pawn, "color": "B"},
                     # "6_2": {"type": pieces.Pawn, "color": "B"},
                     # "6_3": {"type": pieces.Pawn, "color": "B"},
                     # "6_4": {"type": pieces.Pawn, "color": "B"},
                     # "6_5": {"type": pieces.Pawn, "color": "B"},
                     # "6_6": {"type": pieces.Pawn, "color": "B"},
                     # "6_7": {"type": pieces.Pawn, "color": "B"},
                      "0_3": {"type": pieces.Pawn, "color": "B"},
                     "7_0": {"type": pieces.Rook, "color": "B"},
                     "7_1": {"type": pieces.Knight, "color": "B"},
                     # "7_2": {"type": pieces.Bishop, "color": "B"},
                     "7_3": {"type": pieces.Queen, "color": "B"},
                     "7_4": {"type": pieces.King, "color": "B"},
                     # "7_5": {"type": pieces.Bishop, "color": "B"},
                     # "7_6": {"type": pieces.Knight, "color": "B"},
                     "7_7": {"type": pieces.Rook, "color": "B"},
                     "0_0": {"type": pieces.Rook, "color": "W"},
                     # "0_1": {"type": pieces.Knight, "color": "W"},
                     # "0_2": {"type": pieces.Bishop, "color": "W"},
                     "1_3": {"type": pieces.Queen, "color": "W"}, # original is '0_3'
                     "0_4": {"type": pieces.King, "color": "W"},
                     "0_5": {"type": pieces.Bishop, "color": "W"},
                     "0_6": {"type": pieces.Knight, "color": "W"},
                     "0_7": {"type": pieces.Rook, "color": "W"},
                     # "1_0": {"type": pieces.Pawn, "color": "W"},
                     # "1_1": {"type": pieces.Pawn, "color": "W"},
                     # "1_2": {"type": pieces.Pawn, "color": "W"},
                     # "1_3": {"type": pieces.Pawn, "color": "W"},
                     # "1_4": {"type": pieces.Pawn, "color": "W"},
                     # "1_5": {"type": pieces.Pawn, "color": "W"},
                     # "1_6": {"type": pieces.Pawn, "color": "W"},
                     # "1_7": {"type": pieces.Pawn, "color": "W"},
                     "6_2": {"type": pieces.Pawn, "color": "W"},
                     }
