<FirstScreen>:
    GridLayout:
        cols: 1
        padding: 5
        spacing: 5
        Image:
            id: img_id
            size_hint_y: 0.8
        TextInput:
            id: text_id
            size_hint_y: 0.05
        Button:
            text: 'Search Image'
            size_hint_y: 0.15
            on_press: root.search_image()


<RootWidget>:
    FirstScreen:
        id: first_screen
        name: 'first_screen'